-- NOME: ILYS GOMES MAROTO
-- RA: 04241067
-- CRIAÇÃO DO BANCO DE DADOS PARA O PROJETO INDIVIDUAL

DROP DATABASE IF EXISTS 39TALK;
CREATE DATABASE 39TALK;
USE 39TALK;

CREATE TABLE VOCALOID (
IDVOCALOID INT PRIMARY KEY auto_increment,
NOME VARCHAR(256)
);

INSERT INTO VOCALOID (NOME) VALUES
('Hatsune Miku'),
('Kaito'),
('Meiko'),
('Megurine Luka'),
('Kagamine Len'),
('Kagamine Rin');

CREATE TABLE IMAGEMPERFIL (
IDIMAGEMPERFIL INT PRIMARY KEY auto_increment,
IMAGEM VARCHAR(256)
); 

INSERT INTO IMAGEMPERFIL (IMAGEM) VALUES
('../assets/icon/mikuicon.jpg'),
('../assets/icon/kaitoicon.jpg'),
('../assets/icon/meikoicon.jpg'),
('../assets/icon/lukaicon.jpg'),
('../assets/icon/lenicon.jpg'),
('../assets/icon/rinicon.jpg');

CREATE TABLE GENERO(
IDGENERO INT PRIMARY KEY AUTO_INCREMENT,
GENERO VARCHAR(256)
);

CREATE TABLE CONHECIMENTO(
IDCONHECIMENTO INT PRIMARY KEY AUTO_INCREMENT,
COMO VARCHAR(256)
);

CREATE TABLE ATUACAO(
IDATUACAO INT PRIMARY KEY AUTO_INCREMENT,
ATUACAO VARCHAR(256)
);

CREATE TABLE USUARIO(
IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(256),
EMAIL VARCHAR(256) UNIQUE,
SENHA VARCHAR(256),
NASC DATE,
FKATUACAO INT,
FKCONHECIMENTO INT,
FKGENERO INT,

FOREIGN KEY (FKATUACAO) REFERENCES ATUACAO(IDATUACAO),
FOREIGN KEY (FKCONHECIMENTO) REFERENCES CONHECIMENTO(IDCONHECIMENTO),
FOREIGN KEY (FKGENERO) REFERENCES GENERO(IDGENERO)
);

CREATE TABLE JOGO(
IDJOGO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(256)
);

CREATE TABLE PONTUACAO (
IDPONTUACAO INT AUTO_INCREMENT,
FKJOGO INT,
FKUSUARIO INT,
PONTUACAO INT,
VEZESJOGADAS INT,

PRIMARY KEY (IDPONTUACAO, FKJOGO, FKUSUARIO),
FOREIGN KEY (FKJOGO) REFERENCES JOGO(IDJOGO),
FOREIGN KEY (FKUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE PERFIL (
IDPERFIL INT AUTO_INCREMENT,
APELIDO VARCHAR(256),
FKUSUARIO INT,
FKIMAGEM INT,
FKVOCALOID INT,

PRIMARY KEY (IDPERFIL, FKUSUARIO),
FOREIGN KEY (FKUSUARIO) REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY (FKIMAGEM) REFERENCES IMAGEMPERFIL(IDIMAGEMPERFIL),
FOREIGN KEY (FKVOCALOID) REFERENCES VOCALOID(IDVOCALOID)
);

CREATE TABLE MENSAGEM(
IDMENSAGEM INT AUTO_INCREMENT,
MENSAGEM VARCHAR(256),
DATAHORA DATETIME,
FKUSUARIO INT,

PRIMARY KEY (IDMENSAGEM, FKUSUARIO),
FOREIGN KEY (FKUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE POST(
IDPOST INT,
TITULO VARCHAR(256),
TEXTO VARCHAR(256),
IMAGEM VARCHAR(256),
DATAHORA DATETIME,
FKUSUARIO INT,

PRIMARY KEY (IDPOST, FKUSUARIO),
FOREIGN KEY (FKUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);
